default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: recipe_app_rb_development
  username: postgres
  password: div@var9
  host: localhost
  port: 5432

test:
  <<: *default
  database: recipe_app_rb_test
  username: postgres
  password: div@var9
  host: localhost
  port: 5432

production:
  <<: *default
  database: recipe_app_rb_production
  username: recipe_app_rb
  password: <%= ENV["BLOG_APP_DATABASE_PASSWORD"] %>